[build]
  base = "twentytwopips"
  command = "npm run build"
  publish = "twentytwopips/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/**"
  to = "/index.html"
  status = 200
