[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Ensure Netlify doesn't try to run the Next.js plugin check if next/@netlify/plugin-nextjs is present
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Pin a Node version if desired
  NODE_VERSION = "18"

# SPA fallback so client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200